[package]
name = "cosmic-comp"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
authors = ["Victoria Brekenfeld"]

[dependencies]
anyhow = { version = "1.0.51", features = ["backtrace"] }
bitflags = "1.3.2"
slog = "2.7"
slog-term = "2.8"
slog-async = "2.7"
slog-scope = "4.4"
slog-stdlog = "4.1"
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
egui = { version = "0.16", optional = true }
edid-rs = { version = "0.1" }
thiserror = "1.0.26"
xcursor = "0.3.3"

[dependencies.smithay]
version = "0.3"
git = "https://github.com/Smithay/smithay.git"
rev = "1151eea4"
default-features = false
features = ["backend_drm", "backend_gbm", "backend_egl", "backend_libinput", "backend_session_libseat", "backend_udev", "backend_winit", "backend_x11", "desktop", "use_system_lib", "renderer_gl", "renderer_multi", "wayland_frontend", "slog-stdlog"]

[dependencies.smithay-egui]
git = "https://github.com/Smithay/smithay-egui.git"
rev = "5cc416ce"
optional = true

[build-dependencies]
wayland-scanner = "0.29"

[features]
default = []
debug = ["egui", "smithay-egui", "serde", "serde_json"]

[profile.dev]
lto = "thin"

[profile.fastdebug]
inherits = "release"
debug = true

[profile.release]
lto = "fat"

[patch."https://github.com/Smithay/smithay.git"]
smithay = { git = "https://github.com/pop-os/smithay", branch = "main" }