[package]
name = "cosmic-comp"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
authors = ["Victoria Brekenfeld"]

[dependencies]
anyhow = { version = "1.0.51", features = ["backtrace"] }
bitflags = "1.3.2"
slog = "2.7"
slog-term = "2.8"
slog-async = "2.7"
slog-scope = "4.4"
slog-stdlog = "4.1"
egui = { version = "0.16", optional = true }
edid-rs = { version = "0.1" }

[dependencies.smithay]
version = "0.3"
git = "https://github.com/Smithay/smithay.git"
rev = "ab89bda5"
default-features = false
features = ["backend_drm", "backend_gbm", "backend_egl", "backend_libinput", "backend_session_logind", "backend_udev", "backend_winit", "backend_x11", "desktop", "use_system_lib", "renderer_gl", "wayland_frontend", "slog-stdlog"]

[dependencies.smithay-egui]
git = "https://github.com/Smithay/smithay-egui.git"
rev = "cdff1795"
optional = true

[features]
default = []
debug = ["egui", "smithay-egui"]

[patch."https://github.com/Smithay/smithay"]
smithay = { path = "../../tavern/smithay" }