[package]
name = "cosmic-comp"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
authors = ["Victoria Brekenfeld"]

[dependencies]
anyhow = { version = "1.0.51", features = ["backtrace"] }
bitflags = "1.3.2"
slog = { version = "2.7", features = [] } # "release_max_level_debug", "max_level_trace"] }
slog-term = "2.8"
slog-async = "2.7"
slog-journald = "2.2.0"
slog-scope = "4.4"
slog-stdlog = "4.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sendfd = "0.4.1"
egui = { version = "0.19.0", optional = true }
renderdoc = { version = "0.10.1", optional = true }
edid-rs = { version = "0.1" }
png = "0.17.5"
lazy_static = "1.4.0"
log-panics = { version = "2", features = ["with-backtrace"] }
thiserror = "1.0.26"
regex = "1"
xcursor = "0.3.3"
id_tree = "1.8.0"
xkbcommon = "0.4"
indexmap = "1.8.0"
xdg = "^2.1"
ron = "0.7"
libsystemd = "0.5"
wayland-backend = "0.1.0"
wayland-scanner = "0.30.0"
cosmic-protocols = { git = "https://github.com/pop-os/cosmic-protocols", branch = "main", default-features = false, features = ["server"] }

[dependencies.smithay]
version = "0.3"
git = "https://github.com/Smithay/smithay.git"
rev = "2de946cf9e"
default-features = false
features = ["backend_drm", "backend_gbm", "backend_egl", "backend_libinput", "backend_session_libseat", "backend_udev", "backend_winit", "backend_x11", "desktop", "use_system_lib", "renderer_glow", "renderer_multi", "wayland_frontend", "slog-stdlog", "xwayland"]

[dependencies.smithay-egui]
git = "https://github.com/Smithay/smithay-egui.git"
rev = "b2be360015"
features = ["svg"]
optional = true

[features]
default = []
debug = ["egui", "smithay-egui", "renderdoc"]

[profile.dev]
lto = "thin"

[profile.fastdebug]
inherits = "release"
debug = true

[profile.release]
lto = "fat"

[patch."https://github.com/Smithay/smithay.git"]
smithay = { git = "https://github.com/pop-os/smithay", rev = "2a05d8cd64" }
