[package]
name = "cosmic-comp"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
authors = ["Victoria Brekenfeld"]

[dependencies]
anyhow = { version = "1.0.51", features = ["backtrace"] }
bitflags = "1.3.2"
slog = "2.7"
slog-term = "2.8"
slog-async = "2.7"
slog-scope = "4.4"
slog-stdlog = "4.1"

[dependencies.smithay]
version = "0.3"
git = "https://github.com/Smithay/smithay.git"
rev = "a16c307"
default-features = false
features = ["backend_x11", "backend_egl", "desktop", "use_system_lib", "renderer_gl", "wayland_frontend"]